=== enderwigim/1daw/LMSGI/3rd Term/Tests/1/ejercicio1.dtd
<!ELEMENT oferta (vehiculo+)>
  <!ELEMENT vehiculo (marca, modelo, motor, kilometros, precio, extra*, foto*)>
  <!ELEMENT marca (#PCDATA)>
  <!ELEMENT modelo (#PCDATA)>
  <!ELEMENT motor (#PCDATA)>
  <!ELEMENT kilometros (#PCDATA)>
  <!ELEMENT precio (#PCDATA) >
  <!ELEMENT extra (#PCDATA)>
  <!ELEMENT foto (#PCDATA)>
  <!ATTLIST vehiculo matricula ID #REQUIRED>  
  <!ATTLIST modelo color (gris | blanco | azul | rojo) #REQUIRED>
  <!ATTLIST motor combustible (diesel | gasolina) #REQUIRED>
  <!ATTLIST  extra valor CDATA #IMPLIED>

=== enderwigim/1daw/LMSGI/3rd Term/Tests/1/ejercicio1.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE oferta SYSTEM "ejercicio1.dtd">
<oferta><vehiculo matricula="AA1234"><marca>Ford</marca><modelo color="gris">Focus</modelo><motor combustible="gasolina">Duratorc 1.4</motor><kilometros>12500</kilometros><precio>12000</precio><extra valor="250">Pintura metalizada</extra><extra>Llantas de aleaci√≥n</extra><foto>11325.jpg</foto><foto>11326.jpg</foto></vehiculo><vehiculo matricula=" AA5432"><marca>Ford</marca><modelo color="azul">Focus</modelo><motor combustible="diesel">DTI 1.4</motor><kilometros>12500</kilometros><precio>12000</precio><extra>Kit de comunicaciones multimedia</extra><foto>12786.jpg</foto></vehiculo></oferta>
